language: python
python:
  - 3.8
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq graphviz
install:
  - pip install pip -U
  - pip install -r requirements.txt
  - pip install pytest pytest-django flake8 # These are development dependencies
script:
  - flake8
  - pytest
after_success:
 - coveralls